// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/global-params": {
            "get": {
                "description": "Retrieves the global parameters for Babylon, including finality provider details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "babylon"
                ],
                "summary": "Get Babylon global parameters",
                "responses": {
                    "200": {
                        "description": "Global parameters",
                        "schema": {
                            "$ref": "#/definitions/handlers.PublicResponse-services_GlobalParamsPublic"
                        }
                    }
                }
            }
        },
        "/v1/staker/delegations": {
            "get": {
                "description": "Retrieves delegations for a given staker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staker BTC Public Key",
                        "name": "staker_btc_pk",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of delegations and pagination token",
                        "schema": {
                            "$ref": "#/definitions/handlers.PublicResponse-array_services_DelegationPublic"
                        }
                    },
                    "400": {
                        "description": "Error: Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error"
                        }
                    }
                }
            }
        },
        "/v1/unbonding": {
            "post": {
                "description": "Unbonds a delegation by processing the provided transaction details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "unbonding"
                ],
                "summary": "Unbond delegation",
                "parameters": [
                    {
                        "description": "Unbonding Request Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UnbondDelegationRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Request accepted and will be processed asynchronously"
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error"
                        }
                    }
                }
            }
        },
        "/v1/unbonding/eligibility": {
            "get": {
                "description": "Checks if a delegation identified by its staking transaction hash is eligible for unbonding.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "unbonding"
                ],
                "summary": "Check unbonding eligibility",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staking Transaction Hash Hex",
                        "name": "staking_tx_hash_hex",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The delegation is eligible for unbonding"
                    },
                    "400": {
                        "description": "Missing or invalid 'staking_tx_hash_hex' query parameter",
                        "schema": {
                            "$ref": "#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_babylonchain_staking-api-service_internal_types.Error": {
            "type": "object",
            "properties": {
                "err": {},
                "errorCode": {
                    "$ref": "#/definitions/types.ErrorCode"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "handlers.PublicResponse-array_services_DelegationPublic": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.DelegationPublic"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/handlers.paginationResponse"
                }
            }
        },
        "handlers.PublicResponse-services_GlobalParamsPublic": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/services.GlobalParamsPublic"
                },
                "pagination": {
                    "$ref": "#/definitions/handlers.paginationResponse"
                }
            }
        },
        "handlers.UnbondDelegationRequestPayload": {
            "type": "object",
            "properties": {
                "staker_signed_signature_hex": {
                    "type": "string"
                },
                "staking_tx_hash_hex": {
                    "type": "string"
                },
                "unbonding_tx_hash_hex": {
                    "type": "string"
                },
                "unbonding_tx_hex": {
                    "type": "string"
                }
            }
        },
        "handlers.paginationResponse": {
            "type": "object",
            "properties": {
                "next_key": {
                    "type": "string"
                }
            }
        },
        "services.DelegationPublic": {
            "type": "object",
            "properties": {
                "finality_provider_pk_hex": {
                    "type": "string"
                },
                "staker_pk_hex": {
                    "type": "string"
                },
                "staking_tx_hash_hex": {
                    "type": "string"
                },
                "staking_value": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "time_lock_expire": {
                    "type": "integer"
                }
            }
        },
        "services.FinalityProviderDetails": {
            "type": "object",
            "properties": {
                "btc_pk": {
                    "type": "string"
                },
                "commission": {
                    "type": "string"
                },
                "description": {
                    "$ref": "#/definitions/services.finalityProviderDescription"
                }
            }
        },
        "services.GlobalParamsPublic": {
            "type": "object",
            "properties": {
                "covenant_pks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "covenant_quorum": {
                    "type": "integer"
                },
                "finality_providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.FinalityProviderDetails"
                    }
                },
                "max_staking_amount": {
                    "type": "integer"
                },
                "max_staking_time": {
                    "type": "integer"
                },
                "min_staking_amount": {
                    "type": "integer"
                },
                "min_staking_time": {
                    "type": "integer"
                },
                "tag": {
                    "type": "string"
                },
                "unbonding_time": {
                    "type": "integer"
                }
            }
        },
        "services.finalityProviderDescription": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "identity": {
                    "type": "string"
                },
                "moniker": {
                    "type": "string"
                },
                "security_contact": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "types.ErrorCode": {
            "type": "string",
            "enum": [
                "INTERNAL_SERVICE_ERROR",
                "VALIDATION_ERROR",
                "NOT_FOUND",
                "BAD_REQUEST",
                "FORBIDDEN"
            ],
            "x-enum-varnames": [
                "InternalServiceError",
                "ValidationError",
                "NotFound",
                "BadRequest",
                "Forbidden"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
