// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/staker/delegations": {
            "get": {
                "description": "Retrieves delegations for a given staker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Staker BTC Public Key",
                        "name": "staker_btc_pk",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of delegations and pagination token",
                        "schema": {
                            "$ref": "#/definitions/handlers.PublicResponse-array_services_DelegationPublic"
                        }
                    },
                    "400": {
                        "description": "Error: Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_babylonchain_staking-api-service_internal_types.Error": {
            "type": "object",
            "properties": {
                "err": {},
                "errorCode": {
                    "$ref": "#/definitions/types.ErrorCode"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "handlers.PublicResponse-array_services_DelegationPublic": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/services.DelegationPublic"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/handlers.paginationResponse"
                }
            }
        },
        "handlers.paginationResponse": {
            "type": "object",
            "properties": {
                "next_key": {
                    "type": "string"
                }
            }
        },
        "services.DelegationPublic": {
            "type": "object",
            "properties": {
                "finality_provider_pk_hex": {
                    "type": "string"
                },
                "staker_pk_hex": {
                    "type": "string"
                },
                "staking_tx_hash_hex": {
                    "type": "string"
                },
                "staking_value": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "time_lock_expire": {
                    "type": "integer"
                }
            }
        },
        "types.ErrorCode": {
            "type": "string",
            "enum": [
                "INTERNAL_SERVICE_ERROR",
                "VALIDATION_ERROR",
                "NOT_FOUND",
                "BAD_REQUEST"
            ],
            "x-enum-varnames": [
                "InternalServiceError",
                "ValidationError",
                "NotFound",
                "BadRequest"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
