definitions:
  github_com_babylonchain_staking-api-service_internal_types.Error:
    properties:
      err: {}
      errorCode:
        $ref: '#/definitions/types.ErrorCode'
      statusCode:
        type: integer
    type: object
  handlers.PublicResponse-array_services_DelegationPublic:
    properties:
      data:
        items:
          $ref: '#/definitions/services.DelegationPublic'
        type: array
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-array_services_FpDetailsPublic:
    properties:
      data:
        items:
          $ref: '#/definitions/services.FpDetailsPublic'
        type: array
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-array_services_StakerStatsPublic:
    properties:
      data:
        items:
          $ref: '#/definitions/services.StakerStatsPublic'
        type: array
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-services_DelegationPublic:
    properties:
      data:
        $ref: '#/definitions/services.DelegationPublic'
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-services_GlobalParamsPublic:
    properties:
      data:
        $ref: '#/definitions/services.GlobalParamsPublic'
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.PublicResponse-services_OverallStatsPublic:
    properties:
      data:
        $ref: '#/definitions/services.OverallStatsPublic'
      pagination:
        $ref: '#/definitions/handlers.paginationResponse'
    type: object
  handlers.Result:
    properties:
      data: {}
      status:
        type: integer
    type: object
  handlers.UnbondDelegationRequestPayload:
    properties:
      staker_signed_signature_hex:
        type: string
      staking_tx_hash_hex:
        type: string
      unbonding_tx_hash_hex:
        type: string
      unbonding_tx_hex:
        type: string
    type: object
  handlers.paginationResponse:
    properties:
      next_key:
        type: string
    type: object
  services.DelegationPublic:
    properties:
      finality_provider_pk_hex:
        type: string
      is_overflow:
        type: boolean
      staker_pk_hex:
        type: string
      staking_tx:
        $ref: '#/definitions/services.TransactionPublic'
      staking_tx_hash_hex:
        type: string
      staking_value:
        type: integer
      state:
        type: string
      unbonding_tx:
        $ref: '#/definitions/services.TransactionPublic'
    type: object
  services.FpDescriptionPublic:
    properties:
      details:
        type: string
      identity:
        type: string
      moniker:
        type: string
      security_contact:
        type: string
      website:
        type: string
    type: object
  services.FpDetailsPublic:
    properties:
      active_delegations:
        type: integer
      active_tvl:
        type: integer
      btc_pk:
        type: string
      commission:
        type: string
      description:
        $ref: '#/definitions/services.FpDescriptionPublic'
      total_delegations:
        type: integer
      total_tvl:
        type: integer
    type: object
  services.GlobalParamsPublic:
    properties:
      versions:
        items:
          $ref: '#/definitions/services.VersionedGlobalParamsPublic'
        type: array
    type: object
  services.OverallStatsPublic:
    properties:
      active_delegations:
        type: integer
      active_tvl:
        type: integer
      total_delegations:
        type: integer
      total_stakers:
        type: integer
      total_tvl:
        type: integer
      unconfirmed_tvl:
        type: integer
    type: object
  services.StakerStatsPublic:
    properties:
      active_delegations:
        type: integer
      active_tvl:
        type: integer
      staker_pk_hex:
        type: string
      total_delegations:
        type: integer
      total_tvl:
        type: integer
    type: object
  services.TransactionPublic:
    properties:
      output_index:
        type: integer
      start_height:
        type: integer
      start_timestamp:
        type: string
      timelock:
        type: integer
      tx_hex:
        type: string
    type: object
  services.VersionedGlobalParamsPublic:
    properties:
      activation_height:
        type: integer
      confirmation_depth:
        type: integer
      covenant_pks:
        items:
          type: string
        type: array
      covenant_quorum:
        type: integer
      max_staking_amount:
        type: integer
      max_staking_time:
        type: integer
      min_staking_amount:
        type: integer
      min_staking_time:
        type: integer
      staking_cap:
        type: integer
      tag:
        type: string
      unbonding_fee:
        type: integer
      unbonding_time:
        type: integer
      version:
        type: integer
    type: object
  types.ErrorCode:
    enum:
    - INTERNAL_SERVICE_ERROR
    - VALIDATION_ERROR
    - NOT_FOUND
    - BAD_REQUEST
    - FORBIDDEN
    type: string
    x-enum-varnames:
    - InternalServiceError
    - ValidationError
    - NotFound
    - BadRequest
    - Forbidden
info:
  contact: {}
paths:
  /healthcheck:
    get:
      description: Health check the service, including ping database connection
      produces:
      - application/json
      responses:
        "200":
          description: Server is up and running
          schema:
            type: string
      summary: Health check endpoint
  /v1/delegation/:
    get:
      description: Retrieves a delegation by a given transaction hash
      parameters:
      - description: Staking transaction hash in hex format
        in: query
        name: staking_tx_hash_hex
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delegation
          schema:
            $ref: '#/definitions/handlers.PublicResponse-services_DelegationPublic'
        "400":
          description: 'Error: Bad Request'
          schema:
            $ref: '#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error'
  /v1/finality-providers:
    get:
      description: Fetches details of all active finality providers sorted by their
        active total value locked (ActiveTvl) in descending order.
      parameters:
      - description: Pagination key to fetch the next page of finality providers
        in: query
        name: pagination_key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: A list of finality providers sorted by ActiveTvl in descending
            order
          schema:
            $ref: '#/definitions/handlers.PublicResponse-array_services_FpDetailsPublic'
      summary: Get Active Finality Providers
  /v1/global-params:
    get:
      description: Retrieves the global parameters for Babylon, including finality
        provider details.
      produces:
      - application/json
      responses:
        "200":
          description: Global parameters
          schema:
            $ref: '#/definitions/handlers.PublicResponse-services_GlobalParamsPublic'
      summary: Get Babylon global parameters
  /v1/staker/delegation/check:
    get:
      description: |-
        Check if a staker has an active delegation by the staker BTC address (Taproot only)
        Optionally, you can provide a timeframe to check if the delegation is active within the provided timeframe
        The available timeframe is "today" which checks after UTC 12AM of the current day
      parameters:
      - description: Staker BTC address in Taproot format
        in: query
        name: address
        required: true
        type: string
      - description: Check if the delegation is active within the provided timeframe
        enum:
        - today
        in: query
        name: timeframe
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Result
          schema:
            $ref: '#/definitions/handlers.Result'
        "400":
          description: 'Error: Bad Request'
          schema:
            $ref: '#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error'
  /v1/staker/delegations:
    get:
      description: Retrieves delegations for a given staker
      parameters:
      - description: Staker BTC Public Key
        in: query
        name: staker_btc_pk
        required: true
        type: string
      - description: Pagination key to fetch the next page of delegations
        in: query
        name: pagination_key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of delegations and pagination token
          schema:
            $ref: '#/definitions/handlers.PublicResponse-array_services_DelegationPublic'
        "400":
          description: 'Error: Bad Request'
          schema:
            $ref: '#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error'
  /v1/stats:
    get:
      description: Fetches overall stats for babylon staking including tvl, total
        delegations, active tvl, active delegations and total stakers.
      produces:
      - application/json
      responses:
        "200":
          description: Overall stats for babylon staking
          schema:
            $ref: '#/definitions/handlers.PublicResponse-services_OverallStatsPublic'
      summary: Get Overall Stats
  /v1/stats/staker:
    get:
      description: Fetches details of top stakers by their active total value locked
        (ActiveTvl) in descending order.
      parameters:
      - description: Pagination key to fetch the next page of top stakers
        in: query
        name: pagination_key
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of top stakers by active tvl
          schema:
            $ref: '#/definitions/handlers.PublicResponse-array_services_StakerStatsPublic'
        "400":
          description: 'Error: Bad Request'
          schema:
            $ref: '#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error'
      summary: Get Top Staker Stats by Active TVL
  /v1/unbonding:
    post:
      consumes:
      - application/json
      description: Unbonds a delegation by processing the provided transaction details.
        This is an async operation.
      parameters:
      - description: Unbonding Request Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.UnbondDelegationRequestPayload'
      produces:
      - application/json
      responses:
        "202":
          description: Request accepted and will be processed asynchronously
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error'
      summary: Unbond delegation
  /v1/unbonding/eligibility:
    get:
      description: Checks if a delegation identified by its staking transaction hash
        is eligible for unbonding.
      parameters:
      - description: Staking Transaction Hash Hex
        in: query
        name: staking_tx_hash_hex
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: The delegation is eligible for unbonding
        "400":
          description: Missing or invalid 'staking_tx_hash_hex' query parameter
          schema:
            $ref: '#/definitions/github_com_babylonchain_staking-api-service_internal_types.Error'
      summary: Check unbonding eligibility
swagger: "2.0"
